"""add sobrenome to usuarios

Revision ID: 4233c575e124
Revises: a00eee99af50
Create Date: 2026-08-29 20:27:48.621760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4233c575e124'
down_revision: Union[str, Sequence[str], None] = 'a00eee99af50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('sobrenome', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'sobrenome')
    # ### end Alembic commands ###
