"""Adiciona campos de verificacao e reset de senha

Revision ID: 53a9de0d6ddf
Revises: 4233c575e124
Create Date: 2026-08-29 21:19:39.880815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a9de0d6ddf'
down_revision: Union[str, Sequence[str], None] = '4233c575e124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('verification_token', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('reset_token_expira', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'reset_token_expira')
    op.drop_column('usuarios', 'reset_token')
    op.drop_column('usuarios', 'verification_token')
    op.drop_column('usuarios', 'is_verified')
    # ### end Alembic commands ###
